### ISSUE TITLE
スクロールするテーブルに見出しの固定を追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/website-template#112]
データ量が多くて複雑な表組みの場合、スクロールだけでなく見出しを固定したいという要望があることが多い。
複雑な表組みでも対応できるモジュールを作成する。

**Comment by manabuyasuda** [comment]
`position: sticky;`で実装できる。

```scss
.sw-TableWide {
  @include l-Block();
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
}

.sw-TableWide table {
  display: block;
}

.sw-TableWide th,
.sw-TableWide td {
  white-space: nowrap;
}


.sw-TableWide_FixedCol {
  position: sticky;
  left: -1px;
  z-index: 1;
}
```

ポリフィルに[stickybits](https://github.com/dollarshaveclub/stickybits)や[stickyfill](https://github.com/wilddeer/stickyfill)があるけれど動作しなかった。

```js
$('.sw-TableWide_FixedCol').stickybits();
```

`position: sticky;`の[ブラウザ対応状況](https://caniuse.com/#feat=css-sticky)。  
Android 5以上、PCは対応しないとすれば使える。

対応済み
- Chrome 最新版
- Edge 最新版
- Firefox 最新版
- Safari `-webkit`
- （iOS）Safari `-webkit`

未対応
- IE すべて未対応
- Android 4.4.4未満は非対応
