### ISSUE TITLE
改行を制御するモジュールの改修

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/website-template#131]
`.sw-Show`と`.sw-Hide`を併用することができない。
モバイルファーストの考え方で、常に表示か非表示のどちらかが指定されている状態にする。

```scss

    .sw-Hide {
      display: none;
    }
    
    .sw-HideSm {
      display: inline-block;
      
      @include mq-up(sm) {
        display: none;
      }
    }
    
    .sw-HideMd {
      display: inline-block;
      
      @include mq-up(md) {
        display: none;
      }
    }
    
    .sw-Show {
      display: inline-block;
    }
    
    .sw-ShowSm {
      display: none;
      
      @include mq-up(sm) {
        display: inline-block;
      }
    }
    
    .sw-ShowMd {
      display: none;
      
      @include mq-up(md) {
        display: inline-block;
      }
    }
```

  | 0~ | 375px~ | 768px~ | 1024px~ | 1440px~
-- | -- | -- | -- | -- | --
.sw-Hide | hide | hide | hide | hide | hide
.sw-HideSm | show | hide | hide | hide | hide
.sw-HideMd | show | show | hide | hide | hide
.sw-HideLg | show | show | show | hide | hide
.sw-HideXl | show | show | show | show | hide

  | 0~ | 375px~ | 768px~ | 1024px~ | 1440px~
-- | -- | -- | -- | -- | --
.sw-Show | show | show | show | show | show
.sw-ShowSm | hide | show | show | show | show
.sw-ShowMd | hide | hide | show | show | show
.sw-ShowLg | hide | hide | hide | show | show
.sw-ShowXl | hide | hide | hide | hide | show
