### ISSUE TITLE
Remove: SVGの100%表示をやめる

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/website-template#178]
```scss
/**
 * IEのimgとobject要素でもSVGをフルードイメージにします。
 * See: https://hail2u.net/blog/webdesign/max-width-and-svg-on-ie11-and-below.html
 */
[src$=".svg"],
[data$=".svg"] {
  width: 100%;
}
```

サイズ指定が都度必要になってレイアウトしにくい。
バグが起きることも今の所なさそうなので、崩れたときに修正することにする。
