### ISSUE TITLE
Improve: sw-Buttonのスタイルを見直す

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/website-template#283]

**Comment by manabuyasuda** [comment]
Lightning Design Systemを見ていて、`display: inline-flex;`でも問題ないようだった。

`align-items: center;`と`justify-content: center;`を指定した状態で、Chrome・Firefox・Safari（モバイル含む）・IE11とEdge（Parallels Desktop）を検証したが崩れはなかった。

```scss
.sw-Button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
```

アイコン付きのボタンのレイアウトも変更する。
`position: absolute;`スタイルは問題が出にくいので、テキストと横並びをデフォルトとする。
`min-width`を追加して、横幅が狭くテキストが改行した場合にアイコンが小さくならないようにする。
`margin: auto 0;`にすることで、アイコンのx軸に余分なmarginが付かないようにする。

```scss
.sw-Button_More {
  width: 1em;
  min-width: 1em;
  height: 1em;
  margin: auto 0;
  margin-left: 3px;
  font-size: 1em;
  fill: currentColor;

  @include mq(lg) {
    right: rem(12);
  }
}
```
