### ISSUE TITLE
アイコンフォントの位置調整のCSSをlang="ja"に限定する

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/website-template#51]
```scss
@mixin icon {
  font-family: "<%= fontName %>";
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  display: inline-block;
  vertical-align: middle;
  font-style: normal;
  font-variant: normal;
  font-weight: normal;
  line-height: 1;
  text-decoration: none;
  text-transform: none;
  speak: none;
  [lang="ja"] & {
    position: relative;
    top: -0.1em;
  }
}
```

**Comment by manabuyasuda** [comment]
繁体字と簡体字も追加。

```scss
@mixin icon {
  font-family: "<%= fontName %>";
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  display: inline-block;
  vertical-align: middle;
  font-style: normal;
  font-variant: normal;
  font-weight: normal;
  line-height: 1;
  text-decoration: none;
  text-transform: none;
  speak: none;
  [lang="ja"] &,
  [lang^="zh"] & {
    position: relative;
    top: -0.1em;
  }
}
```

韓国語やタイ語はつけないほうがバランスがいい。
