### ISSUE TITLE
チェックボックスとラジオボタンの修正

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/website-template#66]
Windowsでアイコンとテキストが縦にズレてしまう。
このように`position`で位置を合わせる。

```css
.Checkbox + label {
  display: inline-block;
  position: relative;
  padding-left: 1.25em;
  cursor: pointer;
}

.Checkbox + label:before {
  content: "";
  display: inline-block;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  width: 1em;
  height: 1em;
  margin: auto;
  border: 1px solid #767676;
  border-radius: 3px;
  background-repeat: no-repeat;
  background-size: contain;
}
```
