### ISSUE TITLE
borderをcallapse表示にするmixinを追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/website-template#69]
同じ幅のボーダーがついたボックスを並べるときに、隣り合ったボーダーが2倍になってしまう。
box-shadowで指定することで`nth-of-type`などのセレクタを使わずに解決できる。

```scss
// @desc - tableに`border-collapse: collapse;`を指定したような見せ方ができます。`border-radius`を併用するときは表示が崩れるので使用できません。
// @param {String} $color [currentColor] - ボーダーの色を指定します。
// @param {String} $size [1px] - ボーダーのサイズを指定します。
// @example scss - Usage
//
// .foo { @include border-callapse(#888, 2px); }
//
// @example css - CSS output
// .foo {
//   box-shadow: 
//     2px 0 0 0 #888,
//     0 2px 0 0 #888,
//     2px 2px 0 0 #888,
//     2px 2px 0 0 #888 inset;
// }
@mixin border-callapse($color: currentColor, $size: 1px) {
  box-shadow:
    $size 0 0 0 $color,
    0 $size 0 0 $color,
    $size $size 0 0 $color,
    $size $size 0 0 $color inset;
}
```
